#!/usr/bin/env ruby

class Quote

require './lib/loan'

	def run
		market_file, loan_amount_string = ARGV

		offers = Offers.new
		offers.read_in_csv_data(market_file)
		offers.system_total

		loan = Loan.new(loan_amount_string)
		abort(loan.incorrect_amount?) if loan.incorrect_amount? 
		abort(loan.market_has_sufficient?(offers)) if loan.market_has_sufficient?(offers) 

		offers.sorted_pool
		loan.matched(offers)
		loan.total_repayment

		puts "Requested amount: £#{ARGV[1]}"
		puts "Rate: #{percentage(loan.rate)}%"
		puts "Monthly repayment: #{pretty(loan.monthly_repayment)}"
		puts "Total repayment: #{pretty(loan.total_repayment)}"
	end

	def pretty numbers
		sprintf("£%5.2f", numbers)
	end

	def percentage rate
		(rate * 100).round(1)
	end

end

Quote.new.run